version: '3.9'

networks:
  dockerapi-dev:
    driver: bridge
    
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbit", "5672" ]
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - dockerapi-dev
  
  pdf-service:
    image: pdf-service:latest
    depends_on:
      rabbit:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Backend/PdfService/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    networks:
      - dockerapi-dev 
        
  api-orchestrator:
    image: api-orchestrator:latest
    depends_on:
      rabbit:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Backend/PdfConverter.ApiOrchestrator/Dockerfile
    ports:
      - "5001:80"
    environment:
      - RABBITMQ:User=${RABBITMQ_USER}
      - RABBITMQ:Pass=${RABBITMQ_PASS}
      - RABBITMQ:Host=${RABBITMQ_HOST}
      - RABBITMQ:VHost=${RABBITMQ_VHOST}
    networks:
      - dockerapi-dev        